/* eslint-disable */
// tslint:disable
/**
 * Ofcom Connected Nations Broadband API
 * An API based on Connected Nations broadband data.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */
import { Buffer } from "buffer";

export namespace Api {
	export interface BroadbandProvision {
		/**
		 * @description <p>Unique Property Reference Number</p>
		 * @type {number}
		 * @memberof BroadbandProvision
		 */
		'UPRN': number;
		/**
		 * @description <p>A compiled address description based on use of the Ordnance Survey AddressBase fields of the form - Building Name, Building Number, Dependent_ThoroughFare</p>
		 * @type {string}
		 * @memberof BroadbandProvision
		 */
		'AddressShortDescription': string;
		/**
		 * @description <p>Postcode of address, spaces removed</p>
		 * @type {string}
		 * @memberof BroadbandProvision
		 */
		'PostCode': string;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxBbPredictedDown'?: number;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxBbPredictedUp'?: number;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxSfbbPredictedDown'?: number;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxSfbbPredictedUp'?: number;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxUfbbPredictedDown'?: number;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxUfbbPredictedUp'?: number;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxPredictedDown'?: number;
		/**
		 * @type {number}
		 * @memberof BroadbandProvision
		 * minimum: -1
		 */
		'MaxPredictedUp'?: number;
	}

	export interface FixedAvailability {
		/**
		 * @description <p>Postcode of address, spaces removed</p>
		 * @type {string}
		 * @memberof FixedAvailability
		 */
		'PostCode': string;
		'Availability': Api.BroadbandProvision[];
	}

	export interface FixedAvailabilityNotFound {
		/**
		 * @description <p>Postcode of address, spaces removed</p>
		 * @type {string}
		 * @memberof FixedAvailabilityNotFound
		 */
		'PostCode': string;
		/**
		 * @description <p>A human readable error message</p>
		 * @type {string}
		 * @memberof FixedAvailabilityNotFound
		 */
		'ErrorMessage': string;
	}

	export interface GeneralError {
		/**
		 * @description <p>A human readable error message</p>
		 * @type {string}
		 * @memberof GeneralError
		 */
		'ErrorMessage': string;
	}

}
